  version: "3"

  services:
    app:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - mongodb
      environment:
        SPRING_DATA_MONGODB_DATABASE: reactiveSofka
        SPRING_DATA_MONGODB_URI: mongodb+srv://diegob:diegob@cluster0.dgyji.mongodb.net/reactiveSofka?retryWrites=true&w=majority
      links:
        - mongodb
    mongodb:
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - ./data:/data/db